[tool.poetry]
name = "kareef-notebooks"
version = "0.1.0"
description = "Misc notebooks"
authors = ["kareef928"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
